---
title: "Bayesian Modeling and Simulation: Day 4"
date: 2025-08-21
---

# Agenda

- Simulate!
- Fit more models and play with priors in `brms`

# Load packages

```{r}
library(rstan)
library(rstanarm)
library(bayesplot)
library(lme4)
library(tidyverse)
library(brms)
library(HDInterval)
library(HistData)
```

# Simulating from a Stan model

```{r}
galton_lm <- lm(child ~ 1 + parent, data = Galton)
summary(galton_lm)$coef
summary(galton_lm)$sigma

random_parents <- rnorm(1000, 68, 1.78)
galton_sim_data <- list(
  N = 1000,
  x = random_parents,
  alpha = 24,
  beta = 0.65,
  sigma = 2.24
)

galton_sim_stan <- stan(
  file = "simple_regression_rng.stan",
  data = galton_sim_data,
  chains = 4,
  warmup = 1000,
  iter = 2000,
  algorithm = "Fixed_param"
)

galton_sims_df <- as_draws_df(galton_sim_stan)
colnames(galton_sims_df)
ncol(galton_sims_df)
nrow(galton_sims_df)
ggplot(galton_sims_df, aes(`y_sim[1]`)) + geom_histogram()

plot(as.numeric(galton_sims_df[1, 1:1000]) ~ random_parents)
plot(as.numeric(galton_sims_df[4, 1:1000]) ~ random_parents)
```

# Looking at priors

- 

```{r}
default_priors_lm <- default_prior(child ~ 1 + parent, data = Galton)
default_priors_lm
all_priors <- c(set_prior("normal(68, 50)", class = "Intercept"), 
                set_prior("normal(0, 10)", class = "b", coef = "parent"),
                set_prior("student_t(3, 0, 3)", class = "sigma", lb = 0))

galton_brm <- brm(child ~ 1 + parent, data = Galton,
                  chains = 4, warmup = 1000, iter = 2000,
                  prior = all_priors)

summary(galton_brm)

sim_priors <- c(#set_prior("flat", class = "b"),
  set_prior("normal(68.2, 2.2)", class = "Intercept"), 
  set_prior("normal(0.65, 0.04)", class = "b", coef = "parent"),
  set_prior("normal(2.24, 0.05)", class = "sigma", lb = 0))

galton_brm_sims <- brm(child ~ 1 + parent, data = Galton,
                    chains = 4, warmup = 500, iter = 10500,
                    prior = sim_priors, sample_prior = "only")

prior_summary(galton_brm)
prior_summary(galton_brm_sims)

preds <- predict(galton_brm_sims)[, 1]
head(preds)
length(preds)
sigma <- 2.24
Galton$brm_preds1 <- preds + rnorm(928, 0, 2.24)

ggplot(Galton, aes(parent, brm_preds1)) + geom_point()

summary(lm(brm_preds1 ~ 1 + parent, Galton))

summary(galton_brm)
summary(galton_brm_sims)

sim_stanfit <- stan(
  model_code = stancode(galton_brm_sims),
  data = standata(galton_brm_sims),
  chains = 4, warmup = 1000, iter = 2000)

```

# Fit mixed models

```{r}
london <- read_csv("nat_similarity_lex.csv")

# fit with default priors
london_brm1 <- brm(logRT ~ 1 + related + (1|subject_id), data = london,
                   chains = 4, warmup = 2000, iter = 4000)
london_lmer1 <- lmer(logRT ~ 1 + related + (1|subject_id), 
                     data = london)
summary(london_brm1)
summary(london_lmer1)
brm1_posterior <- as_draws_df(london_brm1)
head(brm1_posterior)
nrow(brm1_posterior)
summary(brm1_posterior)
related_hpdi <- hdi(brm1_posterior$b_relatedunrelated)
ggplot(brm1_posterior, aes(b_relatedunrelated)) + geom_histogram() +
  geom_vline(xintercept = related_hpdi, color = "red", linetype = 2)

# try changing priors
default_prior(logRT ~ 1 + related + (1|subject_id), data = london)
london_priors <- c(
  set_prior("normal(0, 2)", class = "b", coef = "relatedunrelated")
)
london_brm1_newpriors <- brm(logRT ~ 1 + related + (1|subject_id), data = london,
                   chains = 4, warmup = 2000, iter = 4000,
                   prior = london_priors)
prior_summary(london_brm1_newpriors)

newprior_posterior <- as_draws_df(london_brm1_newpriors)
head(newprior_posterior)
nrow(newprior_posterior)
summary(newprior_posterior)
related_hpdi <- hdi(newprior_posterior$b_relatedunrelated)
ggplot(newprior_posterior, aes(b_relatedunrelated)) + geom_density() +
  geom_vline(xintercept = related_hpdi, color = "red", linetype = 2) +
  geom_density(aes(x = brm1_posterior$b_relatedunrelated), color = "blue")


```

Random slope

```{r}
# fit with default priors
london_brm2 <- brm(logRT ~ 1 + related + (1+related|subject_id), data = london,
                   chains = 4, warmup = 2000, iter = 4000)
london_lmer2 <- lmer(logRT ~ 1 + related + (1+related|subject_id), 
                     data = london)
summary(london_brm2)
summary(london_lmer2)
brm2_posterior <- as_draws_df(london_brm2)
head(brm2_posterior)
nrow(brm2_posterior)
summary(brm2_posterior)
related_hpdi <- hdi(brm2_posterior$b_relatedunrelated)
ggplot(brm2_posterior, aes(b_relatedunrelated)) + geom_histogram() +
  geom_vline(xintercept = related_hpdi, color = "red", linetype = 2)

# try changing priors
default_prior(logRT ~ 1 + related + (1+related|subject_id), data = london)
london_priors <- c(
  set_prior("normal(0, 2)", class = "b", coef = "relatedunrelated"),
  set_prior("normal(0.05, 0.001)", class = "sd", coef = "relatedunrelated", group = "subject_id")
)
london_priors
london_brm2_newpriors <- brm(logRT ~ 1 + related + (1+related|subject_id), data = london,
                   chains = 4, warmup = 2000, iter = 4000,
                   prior = london_priors)
prior_summary(london_brm2_newpriors)

newprior_posterior <- as_draws_df(london_brm2_newpriors)
head(newprior_posterior)
colnames(newprior_posterior)
nrow(newprior_posterior)
summary(newprior_posterior)
related_hpdi <- hdi(newprior_posterior$b_relatedunrelated)
ggplot(newprior_posterior, aes(b_relatedunrelated)) + geom_density() +
  geom_vline(xintercept = related_hpdi, color = "red", linetype = 2) +
  geom_density(aes(x = brm2_posterior$b_relatedunrelated), color = "blue")

randomslope_hpdi <- hdi(newprior_posterior$sd_subject_id__relatedunrelated)

ggplot(brm2_posterior, aes(sd_subject_id__relatedunrelated)) + geom_density() 
ggplot(newprior_posterior, aes(sd_subject_id__relatedunrelated)) + geom_density() +
  geom_vline(xintercept = randomslope_hpdi, color = "red", linetype = 2) +
  geom_density(aes(x = brm2_posterior$sd_subject_id__relatedunrelated), color = "blue")

```

